# Generated by Django 2.2.5 on 2019-10-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualReality', '0002_auto_20191025_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name_plural': 'Reservation'},
        ),
    ]
